Few trivias
jirik/layman pull request #163
Opened 2020-11-27 13:16 UTC by index-git

Go per commit

2020-11-27 17:29 UTC, jirik commented on CHANGELOG.md
> +- [#28](https://github.com/jirik/layman/issues/28) At first start of Layman, access rights are set so [that only owner of the workspace can read or edit them](doc/security.md#Authorization) for publi
"that only owner of the workspace can read or edit them" tohle myslím není chování, které chceme. U existujících vrstev v personal chceme zachovat REWO, protože dosud měly REWO.

V kódu je to myslím správně, špatně je to jen v dokumentaci, ale raději to prosím ověř.

2020-11-27 17:29 UTC, jirik commented on CHANGELOG.md
> +- [#101](https://github.com/jirik/layman/issues/101) Change [LAYMAN_CLIENT_VERSION](doc/env-settings.md#LAYMAN_CLIENT_VERSION) from `v1.3.0` to `v1.4.0`
Tuhle změnu nevidím v .env filech, ani nevidím daný release. Jeslti je to myšleno jen jako příprava, raději bych s ní počkal, až to bude implementováno.

2020-11-30 13:08 UTC, jirik requested changes
Commit 833051a44bfd6b4b1ef33300079d90239c32054b should reference issue https://github.com/jirik/layman/issues/157. Then this PR is ready.

2020-11-30 13:19 UTC, index-git commented
> Commit [833051a](https://github.com/jirik/layman/commit/833051a44bfd6b4b1ef33300079d90239c32054b) should reference issue #157. Then this PR is ready.

Linked with both #157 and #160

2020-11-30 13:23 UTC, jirik commented
> > Commit [833051a](https://github.com/jirik/layman/commit/833051a44bfd6b4b1ef33300079d90239c32054b) should reference issue #157. Then this PR is ready.
> 
> Linked with both #157 and #160

Good point with #160. If you plan to rebase (not squash) this PR, it;s better to add those references to particular commit messages, not just to PR.

2020-12-01 08:57 UTC, index-git commented
> > > Commit [833051a](https://github.com/jirik/layman/commit/833051a44bfd6b4b1ef33300079d90239c32054b) should reference issue #157. Then this PR is ready.
> > 
> > 
> > Linked with both #157 and #160
> 
> Good point with #160. If you plan to rebase (not squash) this PR, it;s better to add those references to particular commit messages, not just to PR.

Done.

2020-12-01 10:06 UTC, jirik approved these changes

2020-12-01 10:16 UTC, merged