V1.10.0 small items
jirik/layman pull request #226
Opened 2021-01-14 15:43 UTC by index-git

2021-01-15 10:26 UTC, jirik requested changes

2021-01-15 10:26 UTC, jirik commented on src/layman/common/util.py
> +def clear_publication_info(info):
Test that GET Layer|GET Map responses do not contain id and type keys. E.g. in src/layman/layer/rest_test.py, line 312
```
layer_info = client.get(url_for('rest_layer.get', username=username, layername=layername)).get_json()
```

2021-01-15 10:26 UTC, jirik commented on src/layman/common/prime_db_schema/migrate_test.py
> +        workspaces = run_query(f'select count(*) from {DB_SCHEMA}.users;')
rename workspaces to users

2021-01-15 10:26 UTC, jirik commented on src/geoserver/epsg_properties.py
> +    5514: '5514=PROJCS["S-JTSK / Krovak East North",GEOGCS["S-JTSK",DATUM["System Jednotne Trigonometricke Site Katastralni",'
@jirik Add 5514-related WFS test
Consider also tests for other EPSG codes

2021-01-16 12:51 UTC, index-git commented on deps/geoserver/sample/geoserver_data/user_projections/epsg.properties
> +5514=PROJCS["S-JTSK / Krovak East North",GEOGCS["S-JTSK",DATUM["System Jednotne Trigonometricke Site Katastralni",SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],TOWGS84[572.
I think, it is better to have this definition on only one place and this is the second. I would love to hear the reasons.

2021-01-18 11:10 UTC, jirik approved these changes

2021-01-18 11:47 UTC, merged