Rename input sld to input style
jirik/layman pull request #243
Opened 2021-02-09 16:22 UTC by index-git

- [ ] Tests
- [ ] Layman Test Client
- [ ] Changlelog
- [ ] Documentation

2021-02-09 16:43 UTC, index-git commented on src/layman/upgrade/upgrade_v1_10_test.py
> +
Assert also style file existence.

2021-02-09 16:43 UTC, index-git commented on src/layman/upgrade/upgrade_v1_10_test.py
> +
Assert also style file existence.

2021-02-09 16:43 UTC, index-git commented on src/layman/layer/style.py
> +                                           'source',
Remove 'source' for now.

2021-02-09 16:43 UTC, index-git commented on src/layman/layer/style.py
> +    _, _, root_attribute = root.tag.rpartition('}')
Find a way to get an element name without string operation.

2021-02-09 16:43 UTC, index-git commented on src/layman/layer/style.py
> +STYLE_TYPES_DEF = [StyleTypeDef('sld',
Move into `layman.layer.__init__.py`

2021-02-09 16:43 UTC, index-git commented on src/layman/layer/style.py
> +def get_style_type_from_xml_file(style_path):
Move to `layman.layer.filesystem.input_style.py`

2021-02-10 12:05 UTC, jirik requested changes

2021-02-10 12:55 UTC, jirik approved these changes

2021-02-10 13:03 UTC, merged