Patch after wfst prime schema
jirik/layman pull request #342
Opened 2021-04-30 13:26 UTC by jirik

Part of issue #

- [ ] Tests
- ~~Layman Test Client~~
- [ ] Changlelog
- [ ] Documentation

2021-05-01 10:04 UTC, index-git requested changes

2021-05-01 10:04 UTC, index-git commented on src/layman/layer/prime_db_schema/bbox_tasks.py
> +from celery.utils.log import get_task_logger
I think that added test into this commit is the easiest way. And cancel the second pull request.

2021-05-03 11:09 UTC, index-git approved these changes

2021-05-03 11:22 UTC, jirik commented on doc/endpoints.md
> +- Bounding box is updated in asynchronous task after WFS-T request on actions Insert, Update and Delete.
Insert, Update, **Replace**, and Delete.

2021-05-03 12:15 UTC, index-git approved these changes

2021-05-03 12:37 UTC, merged