Patch after wfst geoserver
jirik/layman pull request #344
Opened 2021-05-02 12:56 UTC by index-git

Part of issue #

- [x] Tests
- ~~Layman Test Client~~
- ~~Changlelog~~
- ~~Documentation~~

Optionally
- Add dependency to doc/dependencies.md

2021-05-02 12:59 UTC, index-git commented on src/layman/geoserver_proxy_test.py
> +    geoserver_wfs.clear_cache(workspace)
This should be redundant, but it is not.

2021-05-03 09:55 UTC, jirik requested changes

2021-05-03 09:55 UTC, jirik commented on src/layman/layer/qgis/wms_tasks.py
> +refresh_wms_needed = empty_method_returns_true
Remove this line

2021-05-03 14:46 UTC, jirik requested changes

2021-05-03 14:46 UTC, jirik commented on src/layman/layer/qgis/wms_tasks.py
> +        wms.delete_layer(workspace, layer)
Remove this line

2021-05-03 14:55 UTC, jirik approved these changes

2021-05-04 07:09 UTC, merged