Wfst in celery II
jirik/layman pull request #356
Opened 2021-05-06 09:50 UTC by index-git

Part of issue #159

- ~~Tests~~
- ~~Layman Test Client~~
- ~~Changlelog~~
- ~~Documentation~~

Optionally
- Add dependency to doc/dependencies.md

2021-05-07 07:11 UTC, jirik requested changes

2021-05-07 07:11 UTC, jirik commented on src/layman/common/consts.py
> +REQUEST_METHOD_DELETE = 'delete'
It's little bit strange we are mixing here HTTP requests and WFS requests as they are from different network levels.

I suggest to use one set of variables for HTTP requests and another set for locks (HTTP request names + WFST).

2021-05-07 07:11 UTC, jirik commented on src/layman/common/consts.py
> +REQUEST_METHOD_DELETE = 'delete'
Move it to common/__init__.py

2021-05-07 07:29 UTC, index-git commented on src/layman/common/redis.py
> +    if method not in [consts.REQUEST_METHOD_PATCH, consts.REQUEST_METHOD_DELETE, consts.REQUEST_METHOD_WFST, ]:
rename parameter `method` to `required_lock`

2021-05-10 07:47 UTC, jirik requested changes

2021-05-10 07:47 UTC, jirik commented on src/layman/authz/__init__.py
> +        if workspace and publication_type and not publication_name and request.method == common.REQUEST_METHOD_GET:
Add `.lower()`

2021-05-10 07:47 UTC, jirik commented on src/layman/authz/__init__.py
> +        if request.method == common.REQUEST_METHOD_GET:
Add `.lower()`

2021-05-10 11:14 UTC, jirik approved these changes

2021-05-10 11:20 UTC, merged