Map refresh after layer
jirik/layman pull request #366
Opened 2021-05-14 15:00 UTC by index-git

Part of issue #170

- [x] Tests
- ~~Layman Test Client~~
- [ ] Changlelog
- [ ] Documentation

Optionally
- Add dependency to doc/dependencies.md

2021-05-16 08:12 UTC, jirik requested changes

2021-05-16 08:12 UTC, jirik commented on src/layman/layer_map_relation_test.py
> +def test_map_refresh_after_layer_change():
I suggest to move it to `layman.publication_relation` package

2021-05-16 08:12 UTC, jirik commented on src/layman/util.py
> +def find_maps_for_layer(layer_workspace, layer_name):
Add unit test

2021-05-16 08:21 UTC, jirik commented on src/layman/map/util.py
> +    grep_cmd = f"grep -r -E '{regexp}' {data_dir}"
Change to `f"grep -r -E '{regexp}' {data_dir}  || [[ $? == 1 ]]"`, see https://unix.stackexchange.com/a/427598 for explanation

This hopefully fixes failed test https://github.com/jirik/layman/runs/2584926010?check_suite_focus=true

2021-05-16 14:48 UTC, index-git commented on src/layman/map/filesystem/thumbnail_tasks.py
> +def patch_after_feature_change(self, workspace, map):
What situations are you missing in commit 6f7ccfd0966731f6682a43b3c5c76c6777faa5bb ?

2021-05-16 14:54 UTC, jirik commented on src/layman/map/filesystem/thumbnail_tasks.py
> +def patch_after_feature_change(self, workspace, map):
Check, that map thumbnail was updated after PATCH Layer

2021-05-17 09:52 UTC, jirik requested changes

2021-05-17 09:52 UTC, jirik commented on src/layman/publication_relation/util.py
> +            layer_url = map_layer.get('url', None)
Remove redundant None

2021-05-17 09:52 UTC, jirik commented on src/layman/publication_relation/util_test.py
> +        ('testuser1', 'faslůghdaůslf', set()),
`faslůghdaůslf` -> `faslughdauslf`

2021-05-17 09:52 UTC, jirik commented on test/data/maps/map_1.json
> +{
Move map json to specific subdir of test/data/maps

2021-05-17 09:52 UTC, jirik commented on src/layman/publication_relation/util_test.py
> +    directory = f'/code/test/data/maps/'
Use more directory specific for this test

2021-05-17 09:52 UTC, jirik commented on doc/endpoints.md
> +- Calling WFS-T on a layer that is contained by map whose previous asynchronous chain (POST, PATCH or another WFS-T) is still running causes run of map's WFS-T asynchronous chain after the current on
Calling WFS-T on a layer that is contained by map whose previous asynchronous chain (POST, PATCH or another chain caused by WFS-T) is still running causes run of map's asynchronous chain after the current one is finished.

2021-05-17 09:52 UTC, jirik commented on doc/rest.md
> +- update thumbnail of each [map](models.md#map) that points to this layer.
Remove trailing `.`

2021-05-17 16:34 UTC, jirik approved these changes

2021-05-18 07:08 UTC, merged